#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Android_Mines.Resource", IsApplication=true)]

namespace Android_Mines
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Bomb = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Cell0 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Cell1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Cell2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Cell3 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Cell4 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Cell5 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Cell6 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Cell7 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Cell8 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Closed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Icon = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int ExitButton = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int Field = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int MainChangeName = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int MainExitButton = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int MainNewGameButton = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int MainRestartButton = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int RestartButton = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int ResultsLabel = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int StartNewGameButton = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int StatisticsLabel = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int TopButton = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int TopText = 2131034123;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EndGame = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Menu = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Top = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040010
			public const int AlertName = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int AlertText = 2130968593;
			
			// aapt resource value: 0x7f040009
			public const int Anonimous = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040007
			public const int ChangeName = 2130968583;
			
			// aapt resource value: 0x7f040002
			public const int DefautTop = 2130968578;
			
			// aapt resource value: 0x7f040012
			public const int EmptyNameError = 2130968594;
			
			// aapt resource value: 0x7f040006
			public const int Exit = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int ExitButtonText = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int GameResults = 2130968584;
			
			// aapt resource value: 0x7f04000c
			public const int Loser = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int Name = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int Points = 2130968590;
			
			// aapt resource value: 0x7f040004
			public const int RestartButtonText = 2130968580;
			
			// aapt resource value: 0x7f04000a
			public const int ResultsFormat = 2130968586;
			
			// aapt resource value: 0x7f040005
			public const int StartNewGameButtonText = 2130968581;
			
			// aapt resource value: 0x7f04000f
			public const int StatisticsFormat = 2130968591;
			
			// aapt resource value: 0x7f040001
			public const int TopButtonText = 2130968577;
			
			// aapt resource value: 0x7f04000b
			public const int Winner = 2130968587;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
